### ISSUE TITLE
这个是我环境的问题吗

### ISSUE THREAD

**Issue by aiastia** [cndiandian/zuanbot.com#1]
![FE92AF7F-BB9C-49EA-9A93-ACAD29335500](https://user-images.githubusercontent.com/19776350/151177495-bc321f57-383d-44bc-86b3-3fa538438d13.jpeg)

**Comment by cndiandian** [comment]
是环境的问题，需要PHP的执行环境才行，调用的接口是PHP读取sqlite3的。
