### ISSUE TITLE
配置后页面出现错误

### ISSUE THREAD

**Issue by xincyu** [cndiandian/zuanbot.com#2]
![QQ截图20220510201613](https://user-images.githubusercontent.com/25548537/167626249-d0f24b0c-9854-4c17-8e9e-49e55be3326d.png)
这是什么问题呢？已经是PHP环境了。

**Comment by xincyu** [comment]
等了一会换手机浏览器或者谷歌浏览器都能正常访问了，不知道什么原因

**Comment by cndiandian** [comment]
截图看起来是没有PHP环境造成的错误问题，至于为什么后来再次访问就可以了，不负责的推测可能是之前没配置PHP的缓存。
